train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./load/div2k/DIV2K_train_HR
      repeat: 20
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 48
      scale_max: 4
      augment: true
      sample_q: 2304
  batch_size: 32

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./load/div2k/DIV2K_valid_HR
      first_k: 10
      repeat: 160
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 48
      scale_max: 4
      sample_q: 2304
  batch_size: 32

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: attnlte
  args:
    encoder:
      name: edsr-baseline
      args:
        no_upsampling: true
    imnet_q:
      name: mlp
      args:
        out_dim: 3
        hidden_list: [256,256,256]
    imnet_k:
      name: mlp
      args:
        hidden_list: [256,256]
    imnet_v:
      name: mlp
      args:
        hidden_list: [256,256]
    local_size: 2
    feat_unfold: false
    non_local_attn: true
    multi_scale: [2]
    softmax_scale: 1
    mod_input: true

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 1200
multi_step_lr:
  milestones: [200, 400, 600, 800, 1000]
  gamma: 0.5

epoch_val: 1
epoch_save: 50

resume: ~